--- 
 JOB_ID: "federated-proximal-noniid"
 API_VER: standard
 PARAMS:
   num-rounds: 100
   epochs: 10
   eval-every: 10
   clients-per-round: 3
   batch-size: 10
   lr: 0.01
   mu: 0.01
   seed: 1543080
   exp-seeds: 
     - 734283
     - 963551
     - 822773
     - 469862
     - 241086
 EXPORT:
   history-file: ''