--- 
 JOB_ID: "fedem-noniid"
 API_VER: standard
 PARAMS:
   femnist-num-layers: 6
   celeba-num-layers: 24
   synthetic-num-layers: 0 
   num-clusters: 5
   update-center-every: 2
   num-rounds: 80
   epochs: 3
   eval-every: 10
   clients-per-round: 6 
   batch-size: 10
   lr: 0.01
   seed: 514306
   regul-term: 0.1
   mu: 0.1
   mode: 'no_size'
   poisoning: on
   num_agents: 0.4
   exp-seeds: 
    - 543797
    - 218690
    - 327764
    - 654792
    - 978759
    - 478600
    - 276060
    - 987051
    - 303282
    - 406799
 EXPORT:
   history-file: ''
