--- 
 JOB_ID: "federated-bayes-standard-noniid"
 API_VER: standard
 PARAMS:
   num-rounds: 100
   epochs: 10
   eval-every: 5
   clients-per-round: 6 
   batch-size: 10
   lr: 0.01
   seed: 456897
   sigma: 1.0
   sigma0: 1.0
   gamma: 1.0
   sample-iter: 8
 EXPORT:
   history-file: ''
