--- 
 JOB_ID: "federated-average-noniid"
 API_VER: standard
 PARAMS:
   num-rounds: 20
   epochs: 1
   eval-every: 2
   clients-per-round: 10
   batch-size: 10
   lr: 0.01
 EXPORT:
   history-file: ''