--- 
 JOB_ID: "federated-robust-noniid"
 API_VER: standard
 PARAMS:
   femnist-num-layers: 6
   celeba-num-layers: 12
   num-clusters: 4
   num-rounds: 60
   epochs: 10
   eval-every: 20
   clients-per-round: 30 
   batch-size: 10
   lr: 0.01
   seed: 514306
   poisoning: on
   num_agents: 0.05
   exp-seeds: 
     - 374283
 EXPORT:
   history-file: ''