--- 
 JOB_ID: "federated-robust-noniid"
 API_VER: standard
 PARAMS:
   femnist-num-layers: 6
   celeba-num-layers: 24
   synthetic-num-layers: 0
   num-clusters: 3
   num-rounds: 100
   epochs: 10
   eval-every: 20
   clients-per-round: 15
   batch-size: 10
   num-blocks: 50
   coff-each: 0.4
   lr: 0.01
   seed: 514306
   exp-seeds: 
     - 374283
 EXPORT:
   history-file: ''