--- 
 JOB_ID: "federated-robust-noniid"
 API_VER: standard
 PARAMS:
   femnist-num-layers: 6
   celeba-num-layers: 24
   synthetic-num-layers: 0
   num-clusters: 3
   num-rounds: 80
   epochs: 3
   eval-every: 20
   clients-per-round: 6 
   batch-size: 20
   num-blocks: 50
   coff-each: 0.4
   lr: 0.01
   seed: 514306
   poisoning: on
   num_agents: 0.03
   exp-seeds: 
        - 2870978
        - 3338572
        - 9000652
 EXPORT:
   history-file: ''