--- 
 JOB_ID: "federated-sem-noniid"
 API_VER: standard
 PARAMS:
   num-clusters: 4
   update-center-every: 10
   num-rounds: 60
   epochs: 10
   eval-every: 10
   clients-per-round: 3 
   batch-size: 10
   lr: 0.01
   seed: 514306
   regul-term: 0.1
   mu: 0.1
   mode: 'no_size'
   poisoning: on
   num_agents: 0.05
   exp-seeds: 
     - 374283
     - 693551
     - 322778
     - 269864
     - 410862
 EXPORT:
   history-file: ''
