--- 
 JOB_ID: "federated-sem-noniid"
 API_VER: standard
 PARAMS:
   num-clusters: 4
   update-center-every: 2
   num-rounds: 80
   epochs: 10
   eval-every: 2
   clients-per-round: 3 
   batch-size: 10
   lr: 0.01
   seed: 514306
   regul-term: 0.1
   mu: 0.1
   mode: 'no_size'
   exp-seeds: 
     - 322778
 EXPORT:
   history-file: ''

