--- 
 JOB_ID: "federated-average-noniid"
 API_VER: standard
 PARAMS:
   num-rounds: 100
   epochs: 5
   eval-every: 20
   clients-per-round: 20 
   batch-size: 30
   lr: 0.003
   seed: 514306
   poisoning: on
   num_agents: 0.05
   exp-seeds: 
     - 374283
 EXPORT:
   history-file: ''
