--- 
 JOB_ID: "federated-average-noniid"
 API_VER: standard
 PARAMS:
   num-rounds: 100
   epochs: 10
   eval-every: 10
   clients-per-round: 20 
   batch-size: 10
   lr: 0.01
   seed: 514306
   exp-seeds: 
     - 374283
 EXPORT:
   history-file: ''
