--- 
 JOB_ID: "federated-average-noniid"
 API_VER: standard
 PARAMS:
   num-rounds: 150
   epochs: 1
   eval-every: 20
   clients-per-round: 3
   batch-size: 10
   lr: 0.01
   seed: 1543080
 EXPORT:
   history-file: ''
