--- 
 JOB_ID: "federated-sgd-noniid"
 API_VER: standard
 PARAMS:
   num-rounds: 120
   epochs: 1
   eval-every: 20
   clients-per-round: 40 
   batch-size: 32
   lr: 0.01
   seed: 514306
   exp-seeds: 
     - 374283
 EXPORT:
   history-file: ''