--- 
 JOB_ID: "federated-model-poisoning"
 API_VER: standard
 PARAMS:
   num-rounds: 10 
   epochs: 1
   eval-every: 5
   clients-per-round: 10
   batch-size: 30
   lr: 0.01
   num-agents: 50
   seed: 0
   exp-seeds:
     - 9421
 EXPORT:
   history-file: ''