--- 
 JOB_ID: "saving-models-for-cluster"
 API_VER: standard
 PARAMS:
   num-rounds: 100 
   epochs: 1
   eval-every: 5
   clients-per-round: 10
   batch-size: 10
   lr: 0.01
   seed: 15432080
 EXPORT:
   history-file: ''
